name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_KEY_BASE64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user
            if [ ! -d "ci-cd-webapp" ]; then
              git clone https://github.com/sneha0018/ci-cd-webapp.git
            fi
            cd ci-cd-webapp
            docker stop cicd || true
            docker rm cicd || true
            docker build -t cicd-webapp .
            docker run -d -p 80:80 --name cicd cicd-webapp
          EOF
